@startuml

frame "Browser" {
    [User]
}

frame "Client Komponente"{
    [Client_Frontend]
    [Client_Backend]
    [Samply.Proxy1]
}

node "central Service" {
    [Samply.Broker]
    [Public Key Infrastructure]
}


package "Server Meeting Room Booking" {
    [Samply.Proxy2]
    [Backend_Connector]
    [MRBS]
    [Database]
}

'' Verbindungen
[User] . [Client_Frontend]
[Client_Frontend] -- [Client_Backend]
[Client_Backend] - [Samply.Proxy1]
[Samply.Proxy1] -- [Samply.Broker]
[Samply.Broker] -- [Samply.Proxy2]
[Samply.Broker] - [Public Key Infrastructure]
[Samply.Proxy2] - [Backend_Connector]
[Backend_Connector] -- [Database]
[MRBS] -- [Database]
@enduml