@startuml "Zusammenhänge zwischen Störung, Problem und Fehler beim Service Support"
: Störungsmeldung;
if (Bekannte Ursache ) then (Ja)
: First Level Support Suport ;
else (Nein)
: Problem;
repeat : Problemmanagment Wissensdaten;
repeat while(Ursache gefunden) is (Nein) not (Ja)
: Fehler;
endif
if (Infrastrukturänderung nötig) then (Ja)
: Change Management;
else (Nein)
endif
: Störung beheben;
@enduml