@startgantt
[Entscheidung der Geschäftsführung] lasts 2 days
[Angebot einholen ] lasts 14 days
[Angebot einholen ] starts D+2
[Mitarbeiterinformation] lasts 1 day 
[Mitarbeiterinformation] starts D+2
[Testen des Gerätes 1 ] lasts 1 day 
[Testen des Gerätes 1 ] starts D+16
[Testen des Gerätes 2 ] lasts 2 days
[Testen des Gerätes 2 ] starts D+16
[Testen des Gerätes 3 ] lasts 1 day 
[Testen des Gerätes 3 ] starts D+16
[Auswahl der Lieferanten] lasts 1 day
[Auswahl der Lieferanten] starts D+17
[lieferung] lasts 5 days 
[lieferung] starts D+20
[Raumauswahl] lasts 2 days 
[Raumauswahl] starts D+20
[Elektroinstalation] lasts 2 days
[Elektroinstalation] starts D+20
[Computer aufstellen] lasts 1 day 
[Computer aufstellen] starts D+25
[Mitarbeiterschulung] lasts 7 days
[Mitarbeiterschulung] starts D+26
[Arbeitsaufnahme] lasts 1 day 
[Arbeitsaufnahme] starts D+32

@endgantt