@startuml
' ---------- Global style ----------
top to bottom direction
skinparam actorFontSize 30
skinparam componentStyle rectangle
skinparam wrapWidth 200
skinparam maxMessageSize 200
skinparam BoldColor green
!define B(x) <color:green><b>x</b></color>
' ---------- Actors ----------

actor "Data Consumer\n(Analytics)" as consumer

cloud "Samply BEAM\n B(**beam-file transfer**)" as beam

' ---------- Central DWH ----------
node "Central DWH" as bh_central {

  folder "Storage" as st {
  database "B(FHIR Store)" as blaze_central
  database "B(**S3 central Store**)" as s3
}
  folder "Beam receiver" as raw {
    artifact "B(**.maf.zstd**)" as raw_maf
    artifact "B(**.metadata.json**)" as raw_manifest
    artifact "B(bundle.json)" as fhir_central
    artifact "(Optional) Monitoring logs" as monitoring
    artifact "B(**Storage Service**)" as ingest
    artifact "(Optional) Notification" as notes
    artifact "B(**MAF upload**)" as file_service
    artifact "B(FHIR create/update)" as fhir_up
  }
  artifact "(Optional) Apache Iceberg\nmeta table + genomic tables + FHIR" as curated
  cloud "B(cBioPortal)\nvisualization + analysis" as cbioportal
  artifact "B(Meta-cache API)\nmeta data + MAF pull + FHIR pull" as api
  artifact "(Optional) API\n SQL queries" as iceberg_connect
}

' ---------- Flows (top -> bottom) ----------
beam --> raw_maf
beam --> raw_manifest
beam --> fhir_central
beam --> monitoring
fhir_central --> ingest
raw_maf --> ingest
raw_manifest --> ingest

ingest . notes
ingest --> file_service
ingest --> fhir_up

file_service --> s3
fhir_up --> blaze_central
api <-- cbioportal: import process
s3 .. curated
s3 -- api

blaze_central .. curated

cbioportal <-- consumer
iceberg_connect <-- consumer
curated .. iceberg_connect

@enduml