@startuml

skinparam nodesep 100
skinparam ranksep 500

class Client{}

class Client_Proxy {
    + SendRequest()
}

class Broker {
    + ForwardRequest()
    + ForwardResponse()
    + RegisterService()
}

class Server_Proxy {
    + CallService()
    + SendResponse()
}

class Server {
    + RunService()
}
'' Connections 
Client -|> Client_Proxy : 1 send Request >
Client_Proxy .> Broker: 2 send Message >
Broker .> Client_Proxy: 7 return Result  >
Broker .>"3 forward Request"  Server_Proxy 
Server_Proxy "6 hand offer Request" .> Broker
Server_Proxy -> Server: "4 call Service" >
Server -> Server_Proxy:"5 send Result" >
Broker <.. "0 register Service"  Server


@enduml