@startuml

frame "Browser" {
    [Client]
}

node "central Service" {
    [OAuth]
    [Spot]
    [Broker]
}

package "central Server" {
    [Focus]
    cloud {
        [Server_REST_API]
    }
    database "Mrbs" {
        [Verbis_Raumplaner]
    }
}
'' Verbindungen
[Client] -- [Spot]
[Spot] .. [OAuth]
[Spot] - [Broker]
[Broker] - [Focus]
[Focus] - [Server_REST_API]
[Server_REST_API] -- [Verbis_Raumplaner]
@enduml