@startuml

frame "Browser" {
    [User]
}

node "central Service" {
    [Client]
    [OAuth]
    [Samply_Proxy_Client]
    [Broker]
}

package "central Server" {
    [Samply_Proxy_Server]
    cloud {
        [Server_REST_API]
    }
    database "Mrbs" {
        [Verbis_Raumplaner]
    }
}
'' Verbindungen
[User] - [Client]
[Client] -- [Samply_Proxy_Client]
[Client] . [OAuth]
[Samply_Proxy_Client] - [Broker]
[Broker] - [Samply_Proxy_Server]
[Samply_Proxy_Server] -- [Server_REST_API]
[Server_REST_API] -- [Verbis_Raumplaner]
@enduml