@startuml


frame "mobile App"{
    [Client]
    [OAuth]
}

node "central Service" {
    [Spot]
    [Broker]
}


package "central Server" {
    [Focus]
    cloud {
        [Server_REST_API]
    }
    database "Mrbs" {
        [Verbis_Raumplaner]
    }
}

'' Verbindungen
[Client] .. [OAuth]
[Client] - [Spot]
[Spot] -- [Broker]
[Broker] -- [Focus]
[Focus] -- [Server_REST_API]
[Server_REST_API] - [Verbis_Raumplaner]
@enduml