@startgantt
'' days = hours in this Example 
[1 Türen und Fenster einbauen] lasts 10 days 
[2 Kabel verlegen und anschließen] lasts 25 days 
[2 Kabel verlegen und anschließen] starts D+10 
[3 Fußboden verlegen] lasts 17 days 
[3 Fußboden verlegen] starts D+10
[4 Lichtanlage installieren] lasts 35 days 
[4 Lichtanlage installieren] starts D+35
[5 Schränke montieren] lasts 32 days 
[5 Schränke montieren] starts D+27
[6 Geräte aufstellen] lasts 15 days 
[6 Geräte aufstellen] starts D+70
[7 Geräte anschließen] lasts 15 days 
[7 Geräte anschließen] starts D+85
@endgantt