@startuml
class BestellPosition{
    - nr: interface-anzahl: int
    --
}
class abstract Komponente {
    -id: int
    - preis: double
    --
    + ToString(): string 
}
class Wechselrichter {
    - mppts: int 
    - leistungMppt: double- spannungMppt: double
    --
}
class HybridWechselrichter{
    - lagespannung: double
    - ladestrom: double
    - mayKapazität: double
    --
}
class PvModul {
    -leistung: double- spannung: double
    - laenge: double- breite: doublle
    - hoehe: double 
    --
}
class Batteriespeicher{
    - kapazitaet: double 
    - ladespannung: double
    --
}
class DBVerbindungsManager {
    -dbConneciton: SqlConnection
    - connectionString: string
    --
    + GetDbConnection()
    + GetPvModule(): PvModul[]
    + GetWechselrichter(): Wechselrichter[]
    + GetHybridWechselrichter(): HybridWechselrichter[]
)}

@enduml