@startuml name Videodatenbank_Relation 
entity Kassetten {
    * ID primary key 
    --
    * Bezeichnung 
    * Länge 
}
entity Film {
 * ID primary key 
 --
 * Titel 
 * Länge
 * Jahr 
}
entity Schauspieler {
 * ID
 --
 * Vorname
 * Nachname
}
entity Film_Schauspieler {

}
'' Relations
Kassetten "1" -- "n" Film: hat
Film "1" -- "n" Film_Schauspieler 
Film_Schauspieler "n" -- "1" Schauspieler: spielt

@enduml