@startuml name Verlag
entity Verlag{
    * VerlagsName primary key
    * Vertragsleiter
    * Verlagsaddresse
}

entity Zeitschrift {
    * Titel primary key
    * Ausgabe
    * Preis
}
entity Abonent {
    * Nummer primary key 
    --
    * Name
    * Addresse 

}
entity Zeitschrift_Abo {
    * AZ_id primary key 
    --
    * ANummer foreign key 
    * ZTitel foreign key 
    * Dauer 
    * Beginn
}

Verlag "1" -- "n" Zeitschrift : verlegt

Zeitschrift "1" -- "n" Zeitschrift_Abo
Zeitschrift_Abo "n"  -- "1" Abonent: bezieht | | 

@endeuml