@startuml "Zusammenhänge zwischen Störung, Problem und Fehler beim Service Support"
: Störungsmeldung;
if (Bekannte Ursache ) then (Ja)
: First Level Support Suport ;
else (Nein)
: Problemmanagement;
repeat : Ursache gefunden;
repeat while(Problemmanagment Wissensdaten) is (Nein) not (Ja)
: Ursache gefungenProblemmanagment Wissensdaten;
endif
if (Infrastrukturänderung nötig) then (Ja)
: Change Management;
else (Nein)
endif
: Störung beheben;
@enduml