@startuml Service 
split 
    -[hidden]->
    : Sensor überschreitet Schwellenwert>
split again
    -[hidden]->
    : Datenblatt;
split again 
    -[hidden]->
    : to_Sensordaten;
end split
' Kasten eins
: Prüfen ob 
Wartungsfall vorliegt;
if (XOR) then (Nein)
: kein Wartungsfall>
else (Ja)
: Wartungsfall>
split 
' übergang 
split again
    -[hidden]->
    : Wartungsvorlage|
split again
    -[hidden]->
    : Datenblatt|
split again
-[hidden]->
    : Tabelle "tb_Sensordaten"|
end split
' Kasten zwei 
: Dringlichkeit 
    einordnen;
if (XOR) then 
: hohe driglichkeit;
elseif (XOR) then
: mittlere Dringlichkeit;
else ()
: hohe Dringlichkeit;
endif
split 
: XOR}
split again
    -[hidden]->
    : "tb_Techniker"|
split again
    -[hidden]->
    : Datenblatt|
split again
    -[hidden]->
    : Wartungskalender|
    -[hidden]->
end split
' Kasten drei 
: Terminierung 
 und ggf.
 Materialbestellung;
if (V) then
: Terminierung ist erfolgt;
else
: Materialbestellung;
endif
' letzter Kasten vier
: Information an
 Kunde und
 Techniker;
endif
split
    : Personen sind 
     informiert>
    -[hidden]->
split again
    : Wartungskalendar |
    -[hidden]->   
end split 

@enduml
