@startuml

rectangle "Planungsphase\n(5 Tage)" as A
rectangle "Installation\n(4 Tage)" as B
rectangle "Entwurf\n(2 Tage)" as C
rectangle "Implementierung\n(16 Tage)" as D
rectangle "Testen\n(3 Tage)" as E
rectangle "Kundendoku\n(5 Tage)" as F
rectangle "Testdoku\n(3 Tage)" as G

A --> B
A --> C
B --> D
C --> D
D --> E
D --> F
E --> G

@enduml