@startuml

class BestellPosition {
    - nr: int
    - interfaceAnzahl: int
    --
}

abstract class Komponente {
    - id: int
    - preis: double
    --
    + toString(): string 
}

class Wechselrichter {
    - mppts: int 
    - leistungMppt: double
    - spannungMppt: double
    --
}

class HybridWechselrichter {
    - ladespannung: double
    - ladestrom: double
    - maxKapazitaet: double
    --
}

class PvModul {
    - leistung: double
    - spannung: double
    - laenge: double
    - breite: double
    - hoehe: double 
    --
}

class Batteriespeicher {
    - kapazitaet: double 
    - ladespannung: double
    --
}

class DBVerbindungsManager {
    - dbConnection: SqlConnection
    - connectionString: string
    --
    + GetDbConnection()
    + GetPvModule(): PvModul[]
    + GetWechselrichter(): Wechselrichter[]
    + GetHybridWechselrichter(): HybridWechselrichter[]
}

@enduml